language: php

#services:
#  - docker
#  -

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install
  - cp .env.dist .env
  - curl -sS https://get.symfony.com/cli/installer | bash
  - /home/travis/.symfony/bin/symfony version
  - /home/travis/.symfony/bin/symfony server:start --no-tls -d
#  - docker-compose pull && docker-compose build && docker-compose up -d
#  - docker-compose ps
#  - docker-compose exec php-fpm php bin/console doctrine:database:create --no-interaction
#  - docker-compose exec php-fpm php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

script:
  - ./bin/phpunit
  - ./vendor/bin/behat



