#index:
#    path: /
#    controller: App\Controller\DefaultController::index

process:
  type: rest
  resource: App\Controller\BooksController
  prefix: /v1
  name_prefix: v1_
  defaults: {_format: json}

