#index:
#    path: /
#    controller: App\Controller\DefaultController::index

book:
  type: rest
  resource: App\Controller\BookController
  prefix: /v1
  name_prefix: v1_
  defaults: {_format: json}

